2020-08-15 17:53:45 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 18:07:23 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 18:08:15 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 18:12:54 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:08:15 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:08:55 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:10:37 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2020-08-15 20:10:41 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:11:55 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:12:10 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:12:49 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:13:41 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:13:56 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-15 20:14:01 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-16 14:44:40 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-16 14:44:49 INFO >> line  19 | InOutWindow.__init__  >> Started
2020-08-16 14:45:26 ERRO >> line  79 | DatabaseManager.sql_execute INSERT INTO admin (id, firstname, lastname, pin) VALUES (?, ?, ?, ?), ('4237', 'Sir Lance', 'A Bot', '$2b$12$WVoQX7Yx6mDxuYHt1cYwlusqviuIMdKrH8li.kB.5zlYZciXQw2Jy') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 74, in sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2020-08-16 16:46:54 ERRO >> line  79 | DatabaseManager.sql_execute SELECT student.id, lastname, firstname, 
                ROUND(SUM(JULIANDAY(checkout) - JULIANDAY(checkin)) * 24.0, 2)
                FROM student LEFT OUTER JOIN activity
                ON student.id = activity.id AND checkout IS NOT NULL
                GROUP BY STRFTIME(%W) ORDER BY lastname, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 76, in sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: near "%": syntax error
2020-08-16 16:53:21 ERRO >> line  79 | DatabaseManager.sql_execute SELECT student.id, student.lastname, student.firstname, 
                ROUND(SUM(JULIANDAY(activity.checkout) - JULIANDAY(activity.checkin)) * 24.0, 2),
                FROM student LEFT OUTER JOIN activity
                ON student.id = activity.id AND activity.checkout IS NOT NULL
                GROUP BY student.id, STRFTIME(activity.checkin, '%W') ORDER BY lastname ASC, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 76, in sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: near "FROM": syntax error
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2020-08-16 18:30:42 WARN >> line 593 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2020-08-16 18:32:06 ERRO >> line  79 | DatabaseManager.sql_execute INSERT INTO admin (id, firstname, lastname, pin) VALUES (?, ?, ?, ?), ('4237', 'Sir Lance', 'A Bot', '$2b$12$kuWi3w5.LX7IFJhbSZ.HUesZCd3PtGKYen9kp6CBOD5iLjVEaz4Si') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 74, in sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2020-08-16 19:40:10 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2020-08-17 16:38:56 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 19:46:49 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-06-27 19:47:17 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-06-27 19:48:03 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-06-27 19:49:04 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 19:49:10 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-06-27 19:50:48 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 19:50:53 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:51:41 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-06-27 22:51:41 WARN >> line 655 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-06-27 22:52:30 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:52:31 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:52:40 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:53:26 ERRO >> line  83 | DatabaseManager.sql_execute INSERT INTO admin (id, firstname, lastname, pin) VALUES (?, ?, ?, ?), ('4237', 'Sir Lance', 'A Bot', '$2b$12$ZsTmlamzs.YhrqDW826aneMNMKBdeBjcBDpJpwpf.j6Mtv/zbo1g.') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 78, in sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2021-06-27 22:54:21 ERRO >> line  83 | DatabaseManager.sql_execute INSERT INTO admin (id, firstname, lastname, pin) VALUES (?, ?, ?, ?), ('4237', 'Sir Lance', 'A Bot', '$2b$12$J8ZpfRAdMpHQRtHI2LS1nOQRmzbDhc.YUh44MOkAr0dCRygCcCd/u') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 78, in sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2021-06-27 22:55:20 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:55:23 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-27 22:55:24 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-06-28 08:28:10 ERRO >> line  83 | DatabaseManager.sql_execute INSERT INTO admin (id, firstname, lastname, pin) VALUES (?, ?, ?, ?), ('4237', 'Sir Lance', 'A Bot', '$2b$12$cVLD5NOI3b2Sa1u3GXsLT.c3yCJup4sOQxoqRHQ9T8F7cAs7q3lbC') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 78, in sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2021-06-28 09:03:45 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-28 09:04:16 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-28 09:08:19 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-28 09:09:40 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-28 10:47:13 WARN >> line  33 | DatabaseManager.check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-06-28 10:47:13 WARN >> line 657 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line  37 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-07-01 09:30:34 WARN >> line 837 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-07-02 09:01:45 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-07-02 09:05:43 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-02 09:08:45 ERRO >> line 724 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 3) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 719, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-07-02 09:11:47 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-02 15:36:01 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-02 15:36:12 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:03:45 WARN >> line 855 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-07-04 11:03:45 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-07-04 11:14:01 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:14:19 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:14:30 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:14:52 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:01 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:13 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:27 CRIT >> line  83 | MainWindow.barcode_scanned Invalid Barcode
2021-07-04 11:15:30 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:36 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:44 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:15:52 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:16:13 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-04 11:17:15 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-05 16:48:13 WARN >> line 855 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-07-05 16:48:13 WARN >> line 889 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-07-05 20:02:13 ERRO >> line 724 | DatabaseManager.__sql_execute INSERT INTO student (id, firstname, lastname) VALUES (?, ?, ?), ('1234', None, None) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 719, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: student.firstname
2021-07-06 08:52:21 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-07 08:19:06 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-07 08:20:32 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-07 08:21:09 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-29 22:09:01 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-30 18:00:59 CRIT >> line  90 | MainWindow.barcode_scanned Invalid Barcode
2021-07-30 18:24:51 CRIT >> line  90 | MainWindow.barcode_scanned Invalid Barcode
2021-07-30 18:24:55 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-30 23:12:01 CRIT >> line  90 | MainWindow.barcode_scanned Invalid Barcode
2021-07-30 23:15:32 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-07-31 10:18:38 INFO >> line  19 | InOutWindow.__init__  >> Started
2021-08-01 00:30:44 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:51:07 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:54:01 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:54:11 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:54:19 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:54:26 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 00:54:39 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:09:07 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:09:14 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:09:21 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:09:27 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:34:15 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:35:02 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:35:08 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:35:18 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:35:37 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 01:35:43 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:40:59 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:41:06 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:41:14 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:42:41 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:51:32 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:51:39 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 09:51:43 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:27:14 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:27:57 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:28:18 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:28:23 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:28:29 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:30:46 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:30:54 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:31:01 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:58:11 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:58:18 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 19:58:23 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 20:05:18 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 20:05:23 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 20:05:48 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 21:19:37 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 21:19:43 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 21:19:47 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-01 23:18:04 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0606', 'Paul', 'Emery', 6) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 09:55:45 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 10:01:23 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 10:01:42 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:03:16 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:16:59 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:17:41 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:18:50 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:19:56 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 12:25:30 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 14:40:59 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 14:48:56 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE admin SET id=?, firstname=?, lastname=? WHERE rowid=?, ('9903', 'Dave', 'Woodard', 5) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2021-08-02 16:23:27 INFO >> line  20 | InOutWindow.__init__  >> Started
2021-08-02 21:25:05 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 21:26:37 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 21:31:24 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-02 21:33:20 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-03 09:03:44 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE admin SET id=?, firstname=?, lastname=? WHERE rowid=?, ('9903', 'Joe', 'Smith', 5) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: admin.id
2021-08-04 08:08:19 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 08:09:19 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 09:03:11 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 10:34:45 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 10:36:10 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 10:39:25 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 10:40:52 ERRO >> line 759 | DatabaseManager.__sql_execute INSERT INTO student (id, firstname, lastname) VALUES (?, ?, ?), ('0202', 'Tom', 'Tommy') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 14:53:03 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 14:53:11 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0303', 'Sanjay', 'Baldeosingh', 2) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 15:23:53 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE student SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0202', 'Jon', 'Smith', 28) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: student.id
2021-08-04 23:14:21 ERRO >> line 759 | DatabaseManager.__sql_execute INSERT INTO activity (id, checkin, checkout) VALUES (?, ?, ?), ('9988', 'Katie', 'Woodard', '1234') >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 3, and there are 4 supplied.
2021-08-04 23:16:25 ERRO >> line 759 | DatabaseManager.__sql_execute UPDATE admin SET id=?, firstname=?, lastname=? WHERE rowid=?, ('0303', 'Richard', 'Thomas', 5) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 754, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.IntegrityError: Barcode already exists in the Student Table. Use a different Barcode.
2021-08-06 21:04:04 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:21:18 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:22:16 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:24:03 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:25:40 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:28:43 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:29:59 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 21:45:03 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 22:17:31 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 22:19:22 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-06 22:20:16 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:29:10 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:29:29 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:30:11 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:32:22 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:32:36 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:33:56 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:34:23 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:34:38 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:36:38 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:38:06 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:38:23 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:38:44 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:40:24 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:41:09 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:41:17 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:52:48 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 07:53:33 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:06:17 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:07:55 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:08:20 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:15:33 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:15:47 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:16:32 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:16:44 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:16:56 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:20:40 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:21:49 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:21:57 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:22:42 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:22:47 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:22:52 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:23:07 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:23:16 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:23:36 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:25:00 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:31:08 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2021-08-07 10:31:09 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:31:19 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 10:31:25 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 11:16:51 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2021-08-07 11:16:52 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 11:17:01 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 11:17:19 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2021-08-07 11:17:22 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-07 11:17:31 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:20:25 WARN >> line 923 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-08-08 09:20:25 WARN >> line 957 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-08-08 09:22:45 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:22:55 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:23:49 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:26:22 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:26:39 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:29:19 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:29:25 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:29:31 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:30:18 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:31:21 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-08 09:31:27 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-13 20:13:34 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2021-08-15 12:25:12 WARN >> line 926 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2021-08-15 12:25:12 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2021-08-15 17:02:28 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:05 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:12 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:17 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:20 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:23 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:26 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:28 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:31 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:37 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:17:45 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:02 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:06 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:09 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:11 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:14 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:18 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2021-08-16 20:18:21 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:24 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-16 20:18:27 INFO >> line 139 | InOutWindow.__init__  >> Started
2021-08-17 20:57:08 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2022-01-02 22:24:09 INFO >> line 139 | InOutWindow.__init__  >> Started
2022-01-02 22:24:26 INFO >> line 139 | InOutWindow.__init__  >> Started
2022-01-02 22:27:12 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2022-01-02 22:39:43 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT student.id, student.firstname, student.lastname
                        FROM student JOIN activity ON student.id=activity.id
                        WHERE activity.checkout IS NULL
                        ORDER BY student.lastname ASC, student.firstname ASC, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 792, in __sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: no such table: student
2022-01-02 22:48:29 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT id, firstname, lastname FROM student WHERE id=?, ('1233',) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 790, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.OperationalError: no such table: student
2022-01-02 22:48:29 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT id, firstname, lastname, pin FROM admin WHERE id=?, ('1233',) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 790, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.OperationalError: no such table: admin
2022-01-02 22:48:29 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT student.id, student.firstname, student.lastname
                        FROM student JOIN activity ON student.id=activity.id
                        WHERE activity.checkout IS NULL
                        ORDER BY student.lastname ASC, student.firstname ASC, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 792, in __sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: no such table: student
2022-01-02 22:48:29 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2022-01-02 22:49:08 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2022-01-02 22:49:49 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2022-01-02 22:54:15 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT student.id, student.firstname, student.lastname
                        FROM student JOIN activity ON student.id=activity.id
                        WHERE activity.checkout IS NULL
                        ORDER BY student.lastname ASC, student.firstname ASC, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 792, in __sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: no such table: student
2022-01-02 22:54:22 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT id, firstname, lastname FROM student WHERE id=?, ('4237',) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 790, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.OperationalError: no such table: student
2022-01-02 22:54:22 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT id, firstname, lastname, pin FROM admin WHERE id=?, ('4237',) >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 790, in __sql_execute
    cursor.execute(sql, parameters)
sqlite3.OperationalError: no such table: admin
2022-01-02 22:54:22 ERRO >> line 795 | DatabaseManager.__sql_execute SELECT student.id, student.firstname, student.lastname
                        FROM student JOIN activity ON student.id=activity.id
                        WHERE activity.checkout IS NULL
                        ORDER BY student.lastname ASC, student.firstname ASC, None >> Error with execute
Traceback (most recent call last):
  File "C:\Users\jwoodard\PycharmProjects\TimeTrack4237\DatabaseManager.py", line 792, in __sql_execute
    cursor.execute(sql)
sqlite3.OperationalError: no such table: student
2022-01-02 22:54:22 CRIT >> line 100 | MainWindow.barcode_scanned Invalid Barcode
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2022-01-02 22:54:31 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 926 | DatabaseManager.__check_database  >> File does not exist: files/timetrack.db --> Creating the database file.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: student --> Creating the table.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: activity --> Creating the table.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> table does not exist: admin --> Creating the table.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> index does not exist: activity_id --> Creating the index.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_activity --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_activity --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_student --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_student --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: insert_admin --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: update_admin --> Creating the trigger.
2022-01-02 23:03:15 WARN >> line 960 | DatabaseManager.__check_db_object  >> trigger does not exist: delete_admin --> Creating the trigger.
2022-01-04 14:05:52 INFO >> line 139 | InOutWindow.__init__  >> Started
